spring:
  application:
    name: delivery-service

  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: delivery-service
      auto-offset-reset: earliest

server:
  port: 8082