spring:
  application:
    name: delivery-service

  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: delivery-service
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "com.umesh.shared"
        spring.json.value.default.type: com.umesh.shared.event.NotificationRequestedEvent

    

server:
  port: 8082